### ISSUE TITLE
delete share fails if volume is offline

### ISSUE THREAD

**Issue by Carthaca** [sapcc/manila#113]
https://paste.opendev.org/show/byY9v0xlkp3qGIacOxhE/

a previous delete attempt already offlined the volume, but could not delete.

delete should be idempotent, if the volume is already offline, it should continue deleting.

naive approach: not even try to remove_export or ignore errors
more advanced: check if exports have already been removed

--

just for information, not really required to solve this issue:

how did the volume get into offline state, but not being deleted?:
e.g. due to `NetApp API failed. Reason - 15894:Failed to delete volume "share_XYZ" in Vserver "ma_ABC" because it has one or more clones.  Use the "volume clone show -parent-vserver ma_ABC -parent-volume share_XYZ" command to list clones, and either delete or split the clones and retry the operation.  Use "volume clone split start -vserver <vserver name> -flexclone <clone name>" to split clones. Use "volume delete -vserver <vserver name> -volume <clone name>" to delete clones.`
i.e. it has shares from snapshot, where the split job was not done, yet

**Comment by Carthaca** [comment]
shares end up in `error_deleting`, you may think: we have a nanny doing force delete if stuck for 15 min in that state.

problem: customer may constantly try to cleanup themself, i.e. by resetting state + triggering delete. And that must work eventually when clone split is done

**Comment by kpawar-sap** [comment]
deleting child share while clone split is ongoing is fixed via https://github.com/sapcc/manila/pull/114

**Comment by chuan137** [comment]
The fix #116 soft-delete the volumes if it can't be deleted from backend. The share is deleted from Manila, so we avoid deleting the share again. Since export policies is already deleted, volume is unmounted and offline, we only need to delete the volume when it is possible.
