### ISSUE TITLE
NetAppCmodeClient.modify_volume() needs error handling

### ISSUE THREAD

**Issue by Carthaca** [sapcc/manila#77]
The iter-call is silently swallowing errors at https://github.com/openstack/manila/blob/f03e84ae6212ed80e3b1e56ff289cf13634e9a80/manila/share/drivers/netapp/dataontap/client/client_cmode.py#L2532

Inspiration can be something like https://github.com/openstack/manila/blob/f03e84ae6212ed80e3b1e56ff289cf13634e9a80/manila/share/drivers/netapp/dataontap/client/client_cmode.py#L2320-L2329

What we observed: volume comment not being set on volume created from snapshot (likely due to busy doing clone split)

**Comment by kpawar-sap** [comment]
created PR https://github.com/sapcc/manila/pull/93
